language: node_js
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
node_js:
  - "5.4.0"
  - "4.3.0"
before_script:
  - npm install
notifications:
  email: false
